user_address = f'Your DecentralChain address is: \n\n'
user_seed = f'Your DecentralChain seed is: \n\n' 
secret = f'\n\nDO NOT SHARE your seed phrase with anyone. Store it in a secure and private place that only you have access to.'
dcc_balance = f'Your DecentralCoin balance is: '
private = 'The information was sent to you private by {bot_name}.'
processing = f'Securely processing your request. ⏰'
negative_amount = f'You have to specify an amount greater than zero.'
missing_amount = f'You don\'t have enough amount of tokens to make this transaction.'
missing_token = f'You don\'t have any tokens with this name. To check all your tokens use the command /all_balances'
missing_username = 'You can only tip other users by tagging their username, make sure to include it. Usernames start with \'@\', for example {bot_name}.'
sent_tokens = 'Your tip was successfully sent. Check the details with {bot_name}.'
multi_sent_tokens = 'Your tips are currently being sent. Check the details of each tip with {bot_name}.'
sent_tokens_receipt = 'Your tip to @{recipient_username} was successfully sent. You can check the details of the tip <a href="https://decentralscan.com/tx/{transaction_id}">here</a>.'
sent_missing_parameters = 'The command is not being used correctly. The correct format is /tipping username amount token'
withdrawn_tokens = 'Your withdraw was successful. You can check the details with {bot_name}.'
withdrawn_tokens_receipt = 'Your withdraw was successful. You can check the details of the withdraw <a href="https://decentralscan.com/tx/{transaction_id}">here</a>.'
withdrawn_missing_parameters = f'The command is not being used correctly. The correct format is /withdraw address amount token'
stats = 'Users: {user_count}.\n' \
        'Active last 24h: {active_24}.'